--- #Running tasks Parallely
- hosts: all
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install Apache
      action: yum name=httpd state=installed
      async: 3
      poll: 3
      notify: resatrt httpd
  handlers:
     - name: resart httpd
       action: service name=httpd state=resatarted

