--- # Tag functionality playbook
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  tasks:
    - name: first name
      raw: echo "Monica" > /tmp/LOG
      tags:
       - firstname
    - name: second name
      raw: echo "V" > /tmp/LOG
      tags:
       - secondname

